### PR TITLE
Fix checkbox validation

### PR DESCRIPTION
**Pull request by junomorey**
* removed time availability validation from tutee and tutor model
* added checks in model to ensure at least one time availability is selected in the form

### CODE REVIEW

**Comment by apolevoi** [comment]
Checkbox validation works!!!

**Review by apolevoi — COMMENTED** [review]
How come you delete the validate :has_time_availability from the models?

**Comment by junomorey** [comment]
We actually only want a check to make sure that a form cant be submitted with no time availabilities checked, as opposed to a validation on the model level that makes tutors/tutees invalid if they have no time availabilities. For example, if a tutor only has one time availability left and they're paired with a tutee then they no longer have any more time availabilities, however they are still a valid tutor (since they can add more time availabilities in the future).

**Comment by apolevoi** [comment]
Got it, thank you!

**Pull request merged**
